# Generated by Django 5.0.6 on 2024-07-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_item_on_sale_item_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
