# Generated by Django 5.0.6 on 2024-07-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_item_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
    ]
