# Generated by Django 5.0.6 on 2024-07-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_rename_address_userprofile_address1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
